# Generated by Django 4.2.16 on 2026-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupaplicacion',
            options={'verbose_name': 'Grupo de Aplicación', 'verbose_name_plural': 'Grupos de Aplicación'},
        ),
        migrations.AlterModelOptions(
            name='usergroupaplicacion',
            options={'verbose_name': 'Usuario en Grupo de Aplicación', 'verbose_name_plural': 'Usuarios en Grupos de Aplicación'},
        ),
        migrations.AddField(
            model_name='groupaplicacion',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permisos'),
        ),
        migrations.DeleteModel(
            name='GroupAplicacionPermission',
        ),
    ]
